jobs:
  build:
    if: github.repository == 'doocs/jvm'
    needs: docs
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      with:
        destination-repo: git@gitee.com:Doocs/jvm.git
        source-repo: git@github.com:doocs/jvm.git
    - continue-on-error: true
      name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@main
      with:
        branch: gh-pages
        gitee-password: ${{ secrets.GITEE_PASSWORD }}
        gitee-repo: doocs/jvm
        gitee-username: yanglbme
  docs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - continue-on-error: true
      id: cache
      name: Cache node modules
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        path: node_modules
        restore-keys: '${{ runner.os }}-node-

          '
    - continue-on-error: true
      if: steps.cache.outputs.cache-hit != 'true'
      name: Install dependencies
      run: npm install
    - continue-on-error: true
      name: Build VuePress site
      run: yarn docs:build
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        build_dir: docs/.vuepress/dist
        target_branch: gh-pages
name: Build and deploy
on:
  repository_dispatch:
    types: trigger-ga___deploy.yml
